name: 🚀 Backstop Publish

on:
  workflow_dispatch:
  workflow_call:

permissions:
  actions: write
  contents: write
  pull-requests: write

env:
  NODE_VERSION: 20

jobs:
  backstop-publish-flow:
    name: publish-flow
    runs-on: ubuntu-latest
    steps:
      - name: publish to npm
        uses: ./.github/workflows/npm-push.yml

      - name: publish to dockerhub
        uses: ./.github/workflows/dockerhub-build-push.yml
