name: Test build & publish npm + docker

on:
  workflow_dispatch:
  workflow_call:

permissions:
  actions: write
  checks: write
  contents: write
  pull-requests: write
  packages: write

env:
  NODE_VERSION: 20

jobs:
  test-buid-publish:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        ref: ${{ github.event.pull_request.head.sha || github.ref }}
    
    - name: reference test
      uses: ./.github/actions/backstop-reference-test.yml

  
