name: Test build & publish npm + docker

on:
  workflow_dispatch:
  workflow_call:

permissions:
  actions: write
  checks: write
  contents: write
  pull-requests: write
  packages: write

env:
  NODE_VERSION: 20

jobs:
  test-buid-publish:
    runs-on: ubuntu-latest
    steps:
    - name: reference test
      uses: ./.github/actions/backstop-reference-test.yml

  
